name: mycalendar_app
description: "A calendar application built with Flutter following Clean Architecture."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Presentation
  flutter_bloc: ^9.1.1
  syncfusion_flutter_calendar: ^34.2.6
  google_fonts: ^8.2.1
  font_awesome_flutter: ^11.0.0
  cupertino_icons: ^1.0.8

  # Domain
  equatable: ^2.1.0
  fpdart: ^1.2.0

  # Data
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  timezone: ^0.11.1
  geolocator: ^14.0.3
  geocoding: ^5.0.0

  # Cross-cutting
  get_it: ^9.2.1
  intl: ^0.20.2
  uuid: ^4.6.0
  nepali_utils: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
